/* tslint:disable */
/* eslint-disable */
/**
 * CSC 580 - Image Captioning
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface CaptureResponse
 */
export interface CaptureResponse {
    /**
     * 
     * @type {number}
     * @memberof CaptureResponse
     */
    id?: number;
    /**
     * Capture for given image
     * @type {string}
     * @memberof CaptureResponse
     */
    capture?: string;
}
/**
 * 
 * @export
 * @interface ImageRequest
 */
export interface ImageRequest {
    /**
     * 
     * @type {number}
     * @memberof ImageRequest
     */
    id?: number;
    /**
     * Image as base64 data url
     * @type {string}
     * @memberof ImageRequest
     */
    image?: string;
}

/**
 * CaptioningApi - axios parameter creator
 * @export
 */
export const CaptioningApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Generate an image capture for a given picture
         * @param {ImageRequest} body Image to be captured
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        capturePost: async (body: ImageRequest, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('capturePost', 'body', body)
            const localVarPath = `/capture`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CaptioningApi - functional programming interface
 * @export
 */
export const CaptioningApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CaptioningApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Generate an image capture for a given picture
         * @param {ImageRequest} body Image to be captured
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async capturePost(body: ImageRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CaptureResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.capturePost(body, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * CaptioningApi - factory interface
 * @export
 */
export const CaptioningApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CaptioningApiFp(configuration)
    return {
        /**
         * 
         * @summary Generate an image capture for a given picture
         * @param {ImageRequest} body Image to be captured
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        capturePost(body: ImageRequest, options?: any): AxiosPromise<CaptureResponse> {
            return localVarFp.capturePost(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CaptioningApi - object-oriented interface
 * @export
 * @class CaptioningApi
 * @extends {BaseAPI}
 */
export class CaptioningApi extends BaseAPI {
    /**
     * 
     * @summary Generate an image capture for a given picture
     * @param {ImageRequest} body Image to be captured
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CaptioningApi
     */
    public capturePost(body: ImageRequest, options?: any) {
        return CaptioningApiFp(this.configuration).capturePost(body, options).then((request) => request(this.axios, this.basePath));
    }
}


